AI_Name = "Jarvis"
Function = "Personal Assistant"
Category = "Professional"
Parent_AI = "Edge-TTS"
version = "1st release, 1.0"
AI_Sound = "0 (Jarvis (EN-US))"
AI_Voice_type = "Male"
Greetings = "Sir"